### ISSUE TITLE
How can I get the id of the message I sent to the channel?

### ISSUE THREAD

**Issue by felixq** [eternal-flame-AD/gotify-broadcast#8]
Gotify does not have auto delete or expiration of messages and I need to delete the message after a while but I don't see it returning the id.

**Comment by eternal-flame-AD** [comment]
Thanks for the issue. I am thinking about what API would I provide here because once a broadcast is sent it is sent to every user on different IDs, I am having trouble thinking one without leaking information like user names), and with the current architecture the broadcast is untracked when it has been sent (which is what 'broadcast' means, right?), I will accept a PR for this tho is you are up to it!

**Comment by felixq** [comment]
Thank you
Unfortunately I don't know the language nor can I compile it.
One more question.
Can I use the same user from different devices and everyone will receive the notification?

**Comment by eternal-flame-AD** [comment]
Yes I believe that is how gotify works, you can have multiple clients and they all receive messages
